# Copyright 2025 Canonical Ltd.
# See LICENSE file for licensing details.

"""haproxy-operator charm tls information."""

import logging
import re
import typing
from dataclasses import dataclass

import ops
from charms.tls_certificates_interface.v4.tls_certificates import (
    Certificate,
    TLSCertificatesRequiresV4,
)

TLS_CERTIFICATES_INTEGRATION = "certificates"
HOSTNAME_REGEX = r"[a-z0-9]([-a-z0-9]*[a-z0-9])?(\\.[a-z0-9]([-a-z0-9]*[a-z0-9])?)*"

logger = logging.getLogger()


class TLSNotReadyError(Exception):
    """Exception raised when the charm is not ready to handle TLS."""


class PrivateKeyNotGeneratedError(Exception):
    """Exception raised when the private key has not been generated by the library."""


@dataclass(frozen=True)
class TLSInformation:
    """A component of charm state containing information about TLS.

    Attributes:
        external_hostname: Configured external hostname.
        tls_cert_and_ca_chain: A dict of
            hostname -> certificate obtained from the relation and the Certificate chain.
        private_key: Private key used to generate the CSR.
    """

    external_hostname: str
    tls_cert_and_ca_chain: dict[str, tuple[str, list[Certificate]]]
    private_key: str

    @classmethod
    def from_charm(
        cls, charm: ops.CharmBase, certificates: TLSCertificatesRequiresV4
    ) -> "TLSInformation":
        """Get TLS information from a charm instance.

        Args:
            charm: The haproxy charm.
            certificates: TLS certificates requirer library.

        Raises:
            PrivateKeyNotGeneratedError: When waiting for the private key to be generated.

        Returns:
            TLSInformation: Information about configured TLS certs.
        """
        cls.validate(charm)

        external_hostname = typing.cast(str, charm.config.get("external-hostname"))
        tls_cert_and_ca_chain = {}

        provider_certificates, private_key = certificates.get_assigned_certificates()
        if not private_key:
            raise PrivateKeyNotGeneratedError("Waiting for private key creation")

        for provider_certificate in provider_certificates:
            hostname = provider_certificate.certificate.common_name
            tls_cert_and_ca_chain[hostname] = (
                provider_certificate.certificate,
                provider_certificate.chain,
            )

        return cls(
            external_hostname=external_hostname,
            tls_cert_and_ca_chain=tls_cert_and_ca_chain,
            private_key=private_key,
        )

    @classmethod
    def validate(cls, charm: ops.CharmBase) -> None:
        """Validate the precondition to initialize this state component.

        Args:
            charm: The haproxy charm.

        Raises:
            TLSNotReadyError: if the charm is not ready to handle TLS.
        """
        tls_requirer_integration = charm.model.get_relation(TLS_CERTIFICATES_INTEGRATION)
        external_hostname = typing.cast(str, charm.config.get("external-hostname", ""))

        if not re.match(HOSTNAME_REGEX, external_hostname):
            logger.error(
                "Configured hostname (%s) does not match regex: %s",
                external_hostname,
                HOSTNAME_REGEX,
            )
            raise TLSNotReadyError("Invalid hostname configuration.")

        if (
            tls_requirer_integration is None
            or tls_requirer_integration.data.get(charm.app) is None
        ):
            logger.error("Relation or relation data not ready.")
            raise TLSNotReadyError("Certificates relation or relation data not ready.")
